package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/yaziciahmet/typg/internal/schema"
)

func emitTable(cfg Config, table schema.Table) []byte {
	tVar := tableVar(table.Name)
	tStruct := tableStruct(table.Name)

	imps := newImports()
	imps.addQuery(cfg.queryImport())
	for _, col := range table.Columns {
		imps.addGoType(col.Go)
		if col.Go.IsEnum {
			imps.addModels(cfg.modelsImport())
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by typg %s. DO NOT EDIT.\n\n", cfg.TypgVersion)
	fmt.Fprintf(&b, "package %s\n\n", cfg.Package)
	imps.write(&b)

	fmt.Fprintf(&b, "type %s struct {\n", tStruct)
	for _, col := range table.Columns {
		fmt.Fprintf(&b, "\t%s %s\n", columnField(col.Name), columnType(table.Name, col.Name))
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "var %s = %s{\n", tVar, tStruct)
	for _, col := range table.Columns {
		fmt.Fprintf(&b, "\t%s: %s{},\n", columnField(col.Name), columnType(table.Name, col.Name))
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func (%s) SQLName() string { return %q }\n", tStruct, table.Name)
	fmt.Fprintf(&b, "func (%s) Alias() string { return %q }\n\n", tStruct, table.Name)

	fmt.Fprintf(&b, "func (t %s) Insert() *query.InsertBuilder { return query.Insert(t) }\n", tStruct)
	fmt.Fprintf(&b, "func (t %s) Update() *query.UpdateBuilder { return query.Update(t) }\n", tStruct)
	fmt.Fprintf(&b, "func (t %s) Delete() *query.DeleteBuilder { return query.Delete(t) }\n\n", tStruct)

	for _, col := range table.Columns {
		emitColumnType(&b, imps, table.Name, col)
	}

	return []byte(b.String())
}

func emitModelFile(cfg Config, table schema.Table) []byte {
	imps := newImports()
	for _, col := range table.Columns {
		imps.addGoType(col.Go)
		if col.Go.IsEnum {
			// enums live in the same models package
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by typg %s. DO NOT EDIT.\n\n", cfg.TypgVersion)
	fmt.Fprintf(&b, "package %s\n\n", cfg.modelsPackage())
	imps.write(&b)

	mName := modelName(table.Name)
	fmt.Fprintf(&b, "type %s struct {\n", mName)
	for _, col := range table.Columns {
		fmt.Fprintf(&b, "\t%s %s `db:%q`\n", columnField(col.Name), modelFieldType(imps, col), col.Name)
	}
	fmt.Fprintf(&b, "}\n")
	return []byte(b.String())
}

func modelFieldType(imps *imports, col schema.Column) string {
	base := imps.typeExpr(col.Go)
	if strings.HasPrefix(base, "[]") {
		return base
	}
	if col.Nullable {
		return "*" + base
	}
	return base
}

func emitColumnType(b *strings.Builder, imps *imports, tableName string, col schema.Column) {
	cType := columnType(tableName, col.Name)
	qual := tableName + "." + col.Name

	fmt.Fprintf(b, "type %s struct{}\n\n", cType)
	fmt.Fprintf(b, "func (%s) SQLName() string { return %q }\n", cType, col.Name)
	fmt.Fprintf(b, "func (%s) Qualifier() string { return %q }\n", cType, qual)
	fmt.Fprintf(b, "func (%s) Table() query.Table { return %s }\n\n", cType, tableVar(tableName))

	emitColumnMethods(b, imps, cType, col)
}

func emitColumnMethods(b *strings.Builder, imps *imports, cType string, col schema.Column) {
	caps := columnCapabilities(col)
	valType := valueMethodType(imps, col.Go)

	for _, op := range []struct{ name, query string }{
		{"Eq", "Eq"},
		{"Ne", "Ne"},
	} {
		fmt.Fprintf(b, "func (c %s) %s(v %s) query.Expr { return query.%s(c, v) }\n", cType, op.name, valType, op.query)
		fmt.Fprintf(b, "func (c %s) %sCol(other query.Column) query.Expr { return query.%sCol(c, other) }\n", cType, op.name, op.query)
	}

	if caps.order {
		for _, op := range []struct{ name, query string }{
			{"Gt", "Gt"},
			{"Gte", "Gte"},
			{"Lt", "Lt"},
			{"Lte", "Lte"},
		} {
			fmt.Fprintf(b, "func (c %s) %s(v %s) query.Expr { return query.%s(c, v) }\n", cType, op.name, valType, op.query)
			fmt.Fprintf(b, "func (c %s) %sCol(other query.Column) query.Expr { return query.%sCol(c, other) }\n", cType, op.name, op.query)
		}
	}

	if caps.in {
		emitInMethod(b, imps, cType, col.Go)
	}

	if caps.like {
		fmt.Fprintf(b, "func (c %s) Like(pattern string) query.Expr { return query.Like(c, pattern) }\n", cType)
		fmt.Fprintf(b, "func (c %s) ILike(pattern string) query.Expr { return query.ILike(c, pattern) }\n", cType)
	}

	if caps.contains {
		elemType := arrayElemType(imps, col.Go)
		fmt.Fprintf(b, "func (c %s) Contains(v %s) query.Expr { return query.Contains(c, v) }\n", cType, elemType)
	}

	if col.Nullable {
		fmt.Fprintf(b, "func (c %s) IsNull() query.Expr { return query.IsNull(c) }\n", cType)
		fmt.Fprintf(b, "func (c %s) NotNull() query.Expr { return query.NotNull(c) }\n", cType)
	}
	b.WriteString("\n")
}

func valueMethodType(imps *imports, gt schema.GoType) string {
	if gt.IsEnum {
		return imps.modelsTypeExpr(gt)
	}
	return imps.typeExpr(gt)
}

func emitInMethod(b *strings.Builder, imps *imports, cType string, gt schema.GoType) {
	inType := inMethodType(imps, gt)
	fmt.Fprintf(b, "func (c %s) In(vals ...%s) query.Expr {\n", cType, inType)
	fmt.Fprintf(b, "\targs := make([]any, len(vals))\n")
	fmt.Fprintf(b, "\tfor i, v := range vals { args[i] = v }\n")
	fmt.Fprintf(b, "\treturn query.In(c, args...)\n")
	fmt.Fprintf(b, "}\n\n")
}

func inMethodType(imps *imports, gt schema.GoType) string {
	return arrayElemType(imps, gt)
}

func arrayElemType(imps *imports, gt schema.GoType) string {
	if gt.IsEnum {
		return imps.modelsTypeExpr(gt)
	}
	if strings.HasPrefix(gt.Name, "[]") {
		elem := gt
		elem.Name = strings.TrimPrefix(gt.Name, "[]")
		return imps.typeExpr(elem)
	}
	return imps.typeExpr(gt)
}

func emitEnums(cfg Config, enums []schema.Enum) []byte {
	if len(enums) == 0 {
		return nil
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by typg %s. DO NOT EDIT.\n\n", cfg.TypgVersion)
	fmt.Fprintf(&b, "package %s\n\n", cfg.modelsPackage())

	names := make([]string, len(enums))
	for i, e := range enums {
		names[i] = enumTypeName(e.Name)
	}
	sort.Strings(names)
	byType := map[string]schema.Enum{}
	for _, e := range enums {
		byType[enumTypeName(e.Name)] = e
	}

	for _, typeName := range names {
		e := byType[typeName]
		fmt.Fprintf(&b, "type %s string\n\n", typeName)
		fmt.Fprintf(&b, "const (\n")
		for _, label := range e.Values {
			fmt.Fprintf(&b, "\t%s %s = %q\n", enumConstName(typeName, label), typeName, label)
		}
		fmt.Fprintf(&b, ")\n\n")
	}
	return []byte(b.String())
}

func enumTypeName(pgName string) string {
	return exportIdentifier(pgName)
}

func emitDB(cfg Config) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by typg %s. DO NOT EDIT.\n\n", cfg.TypgVersion)
	fmt.Fprintf(&b, "package %s\n\n", cfg.Package)

	imps := newImports()
	imps.addQuery(cfg.queryImport())
	imps.write(&b)

	funcs := []string{
		"func Select(cols ...query.Column) *query.SelectBuilder { return query.Select(cols...) }",
		"func Insert(t query.Table) *query.InsertBuilder { return query.Insert(t) }",
		"func Update(t query.Table) *query.UpdateBuilder { return query.Update(t) }",
		"func Delete(t query.Table) *query.DeleteBuilder { return query.Delete(t) }",
		"func With(name string) *query.WithBuilder { return query.With(name) }",
		"func Col(table, column string) query.Column { return query.Col(table, column) }",
		"func NewRawCol(sql string, args ...any) query.Column { return query.NewRawCol(sql, args...) }",
		"func Named(name string) query.Table { return query.Named(name) }",
		"func Assign(col query.Column, val any) query.Assignment { return query.Assign(col, val) }",
		"func RawExpr(sql string, args ...any) query.Expr { return query.RawExpr(sql, args...) }",
		"func Eq(col query.Column, val any) query.Expr { return query.Eq(col, val) }",
		"func EqCol(col, other query.Column) query.Expr { return query.EqCol(col, other) }",
		"func Ne(col query.Column, val any) query.Expr { return query.Ne(col, val) }",
		"func NeCol(col, other query.Column) query.Expr { return query.NeCol(col, other) }",
		"func Gt(col query.Column, val any) query.Expr { return query.Gt(col, val) }",
		"func GtCol(col, other query.Column) query.Expr { return query.GtCol(col, other) }",
		"func Gte(col query.Column, val any) query.Expr { return query.Gte(col, val) }",
		"func GteCol(col, other query.Column) query.Expr { return query.GteCol(col, other) }",
		"func Lt(col query.Column, val any) query.Expr { return query.Lt(col, val) }",
		"func LtCol(col, other query.Column) query.Expr { return query.LtCol(col, other) }",
		"func Lte(col query.Column, val any) query.Expr { return query.Lte(col, val) }",
		"func LteCol(col, other query.Column) query.Expr { return query.LteCol(col, other) }",
		"func In(col query.Column, values ...any) query.Expr { return query.In(col, values...) }",
		"func Like(col query.Column, pattern string) query.Expr { return query.Like(col, pattern) }",
		"func ILike(col query.Column, pattern string) query.Expr { return query.ILike(col, pattern) }",
		"func Contains(col query.Column, val any) query.Expr { return query.Contains(col, val) }",
		"func IsNull(col query.Column) query.Expr { return query.IsNull(col) }",
		"func NotNull(col query.Column) query.Expr { return query.NotNull(col) }",
		"func And(exprs ...query.Expr) query.Expr { return query.And(exprs...) }",
		"func Or(exprs ...query.Expr) query.Expr { return query.Or(exprs...) }",
	}
	for _, fn := range funcs {
		fmt.Fprintf(&b, "%s\n\n", fn)
	}
	return []byte(b.String())
}

type imports struct {
	std    []string
	third  map[string]string
	query  string
	models string
}

func newImports() *imports {
	return &imports{third: map[string]string{}}
}

func (i *imports) add(path string) {
	if path == "" {
		return
	}
	for _, s := range i.std {
		if s == path {
			return
		}
	}
	i.std = append(i.std, path)
}

func (i *imports) addQuery(path string) {
	i.query = path
}

func (i *imports) addModels(path string) {
	i.models = path
}

func (i *imports) modelsTypeExpr(gt schema.GoType) string {
	return "models." + gt.Name
}

func (i *imports) addGoType(gt schema.GoType) {
	switch gt.ImportPath {
	case "":
		if gt.Name == "time.Time" || strings.HasPrefix(gt.Name, "[]time.Time") {
			i.add("time")
		}
	default:
		alias := importName(gt.ImportPath)
		i.third[alias] = gt.ImportPath
	}
}

func (i *imports) typeExpr(gt schema.GoType) string {
	if strings.HasPrefix(gt.Name, "[]") && gt.ImportPath != "" {
		alias := importName(gt.ImportPath)
		return "[]" + alias + "." + typeBaseName(strings.TrimPrefix(gt.Name, "[]"))
	}
	switch gt.ImportPath {
	case "":
		return gt.Name
	default:
		alias := importName(gt.ImportPath)
		return alias + "." + typeBaseName(gt.Name)
	}
}

func (i *imports) write(b *strings.Builder) {
	b.WriteString("import (\n")
	sort.Strings(i.std)
	for _, p := range i.std {
		fmt.Fprintf(b, "\t%q\n", p)
	}
	aliases := make([]string, 0, len(i.third))
	for a := range i.third {
		aliases = append(aliases, a)
	}
	sort.Strings(aliases)
	for _, a := range aliases {
		fmt.Fprintf(b, "\t%s %q\n", a, i.third[a])
	}
	if i.query != "" {
		fmt.Fprintf(b, "\tquery %q\n", i.query)
	}
	if i.models != "" {
		fmt.Fprintf(b, "\tmodels %q\n", i.models)
	}
	b.WriteString(")\n\n")
}

func importName(path string) string {
	parts := strings.Split(path, "/")
	return parts[len(parts)-1]
}

func typeBaseName(goType string) string {
	if idx := strings.LastIndex(goType, "."); idx >= 0 {
		return goType[idx+1:]
	}
	return goType
}
